# ---------------------------------------------------------------------------
# Stage 1 — install dependencies & build TypeScript
# ---------------------------------------------------------------------------
FROM node:22-bookworm-slim AS builder

WORKDIR /build

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Skip bundled Chromium — we use system Chromium in the runtime stage
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

COPY package.json ./

# Use npm install (not npm ci) because there is no committed package-lock.json.
# This generates package-lock.json inside the builder layer so the runtime
# stage can use npm ci for a deterministic production install.
RUN npm install

COPY tsconfig.json ./
COPY src/ ./src/

RUN npm run build

# ---------------------------------------------------------------------------
# Stage 2 — runtime image
# ---------------------------------------------------------------------------
FROM node:22-bookworm-slim AS runtime

# Install system Chromium and its dependencies.
# Let apt resolve the correct lib versions for Debian 12 (Bookworm) automatically
# instead of pinning individual lib package names that can change across releases.
RUN apt-get update && apt-get install -y --no-install-recommends \
      chromium \
      fonts-liberation \
      fonts-noto-cjk \
      ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV NODE_ENV=production
ENV TZ=Asia/Jerusalem

WORKDIR /app

# Copy package.json and the lock file generated by the builder stage,
# then use npm ci for a deterministic, auditable production install.
COPY package.json ./
COPY --from=builder /build/package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

# Compiled output from builder
COPY --from=builder /build/dist ./dist

# node:22-bookworm-slim already ships with a 'node' user at UID/GID 1000.
# Use it directly — no need to create a new user (which would conflict).
# compose.yml sets user: "1000:1000" which maps to this same built-in user.
RUN mkdir -p /app/cache && chown -R node:node /app

USER node

CMD ["node", "dist/index.js"]
